runtime: python37
api_version: 1
threadsafe: true

handlers:
  - url: /(community|funcast|gamejam)?
    script: main.app
    secure: always
    http_headers:
      Strict-Transport-Security: 'max-age=604800; includeSubDomains; preload'
  - url: /static/(.*)
    static_files: static/\1
    upload: static/(.*)
    secure: always
    http_headers:
      Strict-Transport-Security: 'max-age=604800; includeSubDomains; preload'
  - url: /favicon.ico
    static_files: static/favicon.ico
