runtime: python37

handlers:
  - url: /(community|discord|funcast|gamejam)?
    secure: always
    script: auto
  - url: /static/(.*)
    static_files: static/\1
    upload: static/(.*)
    secure: always
    http_headers:
      Strict-Transport-Security: 'max-age=604800; includeSubDomains; preload'
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
    secure: always
